import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
await page.goto('http://localhost:5183', { waitUntil: 'networkidle', timeout: 30000 });
await page.waitForTimeout(2500);
await page.evaluate(() => document.getElementById('skills')?.scrollIntoView({ block: 'start' }));
await page.waitForTimeout(1500);
await page.evaluate(() => window.scrollBy(0, 200));
await page.waitForTimeout(2000);
await page.screenshot({ path: 'shots/skills-new2.png' });
await browser.close();
